<?php

/**
 * Created by PhpStorm.
 * User: williamzid
 * Date: 2016/10/17
 * Time: 下午6:04
 */
class DirtyWordsFilter extends php_user_filter
{
    public function filter($in, $out, &$consumed, $closing)
    {
        //parent::filter($in, $out, $consumed, $closing); // TODO: Change the autogenerated stub
        $words = array('fuck', 'dirt', 'slut');
        $wordData = array();
        foreach ($words as $word) {
            $replacement = array_fill(0, mb_strlen($word), '*');
            $wordData[$word] = implode('', $replacement);
        }
        $bad = array_keys($wordData);
        $good = array_values($wordData);

        while ($bucket = stream_bucket_make_writeable($in)) {
            $bucket->data = str_replace($bad, $good, $bucket->data);

            $consumed += $bucket->datalen;

            stream_bucket_append($out, $bucket);
        }
        return PSFS_PASS_ON;
    }
}



